apiVersion: v1
data:
  panel: "true"
kind: ConfigMap
metadata:
  name: template-mlflowcard-card
  namespace: krateo-system
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: template-mlflowcard-card
  namespace: krateo-system
spec:
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      name: template-mlflowcard-customform
      namespace: krateo-system
      resource: customforms
      verb: GET
  - template:
      apiVersion: core.krateo.io/v1alpha1
      name: mlflowcard
      namespace: krateo-system
      resource: compositiondefinitions
      verb: DELETE
  app:
    template:
      color: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end }
      content: Card del modello presente nel model registry di MLflow
      icon: fa-brain
      tags: krateo-system,1.0.0
      title: model1 #${ .getMLflowModel.metadata.name }
      #status: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | "Ready:" + .status }
  propsRef:
    name: template-mlflowcard-card
    namespace: krateo-system
  type: card
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/krateo-system/compositiondefinitions/mlflowcard"
    verb: GET
    headers:
    - 'Accept: application/json'
  - name: getMLflowModel
    path: "/apis/mlflow.example.com/v1alpha1/namespaces/krateo-system/mlflowmodels/model1"
    verb: GET
    headers:
    - 'Accept: application/json'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: template-mlflowcard-customform
  namespace: krateo-system
data:
  onSubmitId: submit
  onSubmitVerb: POST
  payloadFormKey: spec
---
apiVersion: templates.krateo.io/v1alpha1
kind: CustomForm
metadata:
  name: template-mlflowcard-customform
  namespace: krateo-system
spec:
  type: customform
  propsRef:
    name: template-mlflowcard-customform
    namespace: krateo-system
  actions:
    - template:
        id: submit
        apiVersion: composition.krateo.io/v1-0-0
        verb: POST
        resource: mlflowcards
        payloadToOverride:
        - name: metadata.name
          value: ${ mlflow.run.name }
        - name: metadata.namespace
          value: ${ "krateo-system" }
  app:
    template:
      schema: ${ .getCRD | .spec.versions[] | select(.name == "v1-0-0") | .schema.openAPIV3Schema.properties.spec.properties }
      # propertiesToHide: 
      # - mlflow.properties.credentials
      # - mlflow.properties.repo
      # - repo
  api:
  - name: getCRD
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/mlflowcards.composition.krateo.io"
    verb: GET
    headers:
    - 'Accept: application/json'
  - name: getMLflowModel
    path: "/apis/mlflow.example.com/v1alpha1/namespaces/krateo-system/mlflowmodels/model1"
    verb: GET
    headers:
    - 'Accept: application/json'


